name: unique_ptr Homework

on: [push, pull_request]

jobs:
  unique_ptr:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: mkdir homework/unique_ptr/build
      run: mkdir homework/unique_ptr/build
    - name: Compile
      working-directory: homework/unique_ptr/build
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: homework/unique_ptr/build
      run: ctest -V

  valgrind:
    runs-on: ubuntu-latest
    steps:
    - name: Install valgrind
      run: sudo apt-get update && sudo apt-get install valgrind
    - name: Check out code
      uses: actions/checkout@master
    - name: mkdir homework/unique_ptr/build
      run: mkdir homework/unique_ptr/build
    - name: Compile
      working-directory: homework/unique_ptr/build
      run: |
        cmake ..
        make
    - name: Run tests with valgrind
      working-directory: homework/unique_ptr/build
      run: valgrind --leak-check=full --show-leak-kinds=all -v ./unique_ptr-ut